# Generated by Django 4.1.13 on 2024-06-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0005_contactoemergencia_numero_documento_cntemerg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento_usuario',
            field=models.CharField(default='', max_length=20),
        ),
    ]
